name: AutoCheck
run-name: Verifying Pushed Codes of ${{ github.actor }} 

on: [push, pull_request]
jobs:
  
  vm-testing:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - shell: bash
      
      # Building from Source Code
        name: Building from Source Files
        run: |
          cmake -B build .
          cd build/
          sudo make install
      
      # Generating Configuration Files
      - name: Generating Configuration Files
        run: |
          bash .github/scripts/vm-testing/gen-config.sh

      # Executing Binary
      - name: Executing Binary
        run: |
          cd .github/samples
          qsort
      
      # Checking If Everything Working Perfectly
      - name: Verifying Files
        run: |
          bash .github/scripts/vm-testing/verify-files.sh

  debian-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - shell: bash

      # Updating the Source Code Information
        name: Updating the Source Code
        run: |
          # Updates the Source Code Version
          bash .github/scripts/debian-package/update-code.sh "${{ vars.VER }}"

      # Generating Files
      - name: Compiling Files
        run: |
          echo .gitignore>.gitignore
          echo build/>>.gitignore
          cmake -B build .
          cd build/
          make

      # Modifying Debian Installer Information
      - name: Modifying Debian Installer Information
        run: |
          bash .github/scripts/debian-package/update-installer.sh "${{ vars.VER }}"
          
      # Signing Files
      - name: Updating Files
        run: |
          bash .github/scripts/debian-package/commit.sh

      # Pushing Files
      - name: Pushing Files
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}