name: Release
run-name: Releasing Packages from main branch

on:
  workflow_run:
    workflows: [AutoCheck]
    branches: [main]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master
        with: 
          fetch-depth: 0

      - shell: bash
        name: Building packages
        run: |
          cmake -B build .
          cd build/
          make deb
          cd ..
          mv qsort-debian.deb qsort_v${{ vars.VER }}_1_amd64.deb

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "${{ vars.VER }}"
          prerelease: ${{ vars.PRE_RELEASED }}
          files: |
            qsort_v${{ vars.VER }}_1_amd64.deb
  
  skip-task:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - shell: bash
        run: |
          echo "Error: AutoCheck Failed, So no Packages are released."
          exit