name: AutoCheck
run-name: Verifying Pushed Codes of ${{ github.actor }} 

on: [push, pull_request]
jobs:
  
  vm-testing:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - shell: bash
      

      # Building from Source Code
        name: Building from Source Files
        run: |
          make
      
      # Generating Configuration Files
      - name: Generating Configuration Files
        run: |
          make install

          cd ~
          mkdir Documents Pictures Videos Music

      # Executing Binary
      - name: Executing Binary
        run: |
          cd .github/samples
          qsort
      
      # Checking If Everything Working Perfectly
      - name: Verifying Files
        run: |
          if [[ -f "$HOME/Documents/document.doc" ]]; then
              echo "Document Verification Complete"
          else
              echo "Document Verification Failed"
              exit 1
          fi

          if [[ -f "$HOME/Pictures/blackhole.jpg" ]]; then
              echo "Picture Verification Complete"
          else
              echo "Picture Verification Failed"
              exit 1
          fi

          if [[ -f "$HOME/Videos/horse.mp4" ]]; then
              echo "Video Verification Complete"
          else
              echo "Video Verification Failed"
              exit 1
          fi

          if [[ ! -f "$HOME/add.py" ]]; then
              echo "General Files Verification Complete"
          else
              echo "General Files Verification Failed"
              exit 1
          fi


